<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
		<OutDir>..\..\Bin</OutDir>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BooleanDemo.cs" />
    <Using Include="DemoScenes" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DemoScenes\DemoScenes.csproj" />
    <ProjectReference Include="..\..\Core\Nori.Core.csproj" />
    <ProjectReference Include="..\..\Host\GLU\Nori.GLU.csproj" />
    <ProjectReference Include="..\..\Host\WPF\Nori.Host.WPF.csproj" />
    <ProjectReference Include="..\..\Lux\Nori.Lux.csproj" />
  </ItemGroup>

  <ItemGroup>
     <ProjectReference Include="..\..\Tools\Generate\Nori.Gen.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>
</Project>
