// ────── ╔╗
// ╔═╦╦═╦╦╬╣ TypeFace.cs
// ║║║║╬║╔╣║ Wrapper around a FreeType typeface
// ╚╩═╩═╩╝╚╝ ───────────────────────────────────────────────────────────────────────────────────────
using Nori.FreeType;
namespace Nori;
using static Nori.FreeType.FreeType;
using Ptr = nint;

#region class TypeFace -----------------------------------------------------------------------------
/// <summary>TypeFace is a wrapper around a FreeType typeface</summary>
/// The typeface can be loaded from a TTF/OTF file, or from a memory block 
/// containing that data. A typeface is a font file + a given pixel size
public class TypeFace {
   // Constructors -------------------------------------------------------------
   /// <summary>Load a typeface from a TTF file</summary>
   public TypeFace (string fontFile, int pixelSize, double gamma = 1.5) {
      try {
         mGamma = gamma;
         Check (NewFace (Library, fontFile, 0, out mFace));
         InitFont (pixelSize);
      } catch (Exception e) {
         throw new IOException ($"Unable to load TypeFace from file '{fontFile}'", e);
      }
   }
   readonly HFace mFace;   // Freetype handle

   /// <summary>Load a typeface from a font file that is already loaded into memory</summary>
   public TypeFace (byte[] data, int pixelSize) {
      mFaceRawBlock = GCHandle.Alloc (data, GCHandleType.Pinned);
      Check (NewFace (Library, mFaceRawBlock.AddrOfPinnedObject (), data.Length, 0, out mFace));
      InitFont (pixelSize);
   }
   readonly GCHandle mFaceRawBlock;    // Unmanaged-memory copy of the byte-array

   /// <summary>Create a new TypeFace from a given one (with a different pixel-size)</summary>
   public TypeFace (TypeFace tf, int pixelSize) {
      mGamma = tf.Gamma; mFace = tf.mFace;
      InitFont (pixelSize);
   }

   // Used by LoadAtlas (the pre-baked path needs no FreeType at all)
   TypeFace () { }

   // Properties ---------------------------------------------------------------
   /// <summary>Returns the indices of all glyphs available in this font</summary>
   public IReadOnlyList<uint> AllGlyphs { get { _ = Map; return mAllGlyphs!; } }
   List<uint>? mAllGlyphs;

   /// <summary>The different encodings available for this font</summary>
   internal FTEncoding[] Encodings {
      get {
         if (mEncodings == null) {
            int count = mRec.CCharMaps;
            mEncodings = new FTEncoding[count];
            unsafe {
               IntPtr* array = (IntPtr*)mRec.Charmaps;
               for (int i = 0; i < count; i++) {
                  CharMap cmap = Marshal.PtrToStructure<CharMap> (*array);
                  mEncodings[i] = cmap.Encoding;
                  array++;
               }
            }
         }
         return mEncodings;
      }
   }
   FTEncoding[]? mEncodings;

   /// <summary>Returns an always-available default typeface (Roboto, 18px)</summary>
   /// On the desktop this rasterizes the TTF with FreeType. On the browser (no native
   /// FreeType) it loads the nearest pre-baked glyph atlas (see SaveAtlas / LoadAtlas,
   /// baked offline by Tools/FontBake).
   public static TypeFace Default {
      get {
         if (mDefault == null) {
            int size = (int)(9 * Lux.DPIScale + 0.5);
            if (OperatingSystem.IsBrowser ()) {
               int baked = BakedSizes.MinBy (a => Math.Abs (a - size));
               mDefault = LoadAtlas (Lib.ReadBytes ($"nori:GL/Fonts/Roboto-Regular-{baked}.atlas"));
            } else
               mDefault = new (Lib.ReadBytes ("nori:GL/Fonts/Roboto-Regular.ttf"), size);
         }
         return mDefault;
      }
      set => mDefault = value;
   }
   static TypeFace? mDefault;

   /// <summary>The pixel-sizes at which atlases are baked (by Tools/FontBake)</summary>
   /// These cover the common devicePixelRatio values (1, 1.25, 1.5, 2, 3) at the 9px base size
   public static readonly int[] BakedSizes = [9, 11, 14, 18, 27];

   /// <summary>Set the Gamma value to use when rasterizing the font</summary>
   /// Monitor gamma values range from 1.8 to 2.2 typically, so we pick 2.0 as a close-enough
   /// default. The gamma correction is needed because the 'glyph bitmaps' generated by FreeType
   /// are 'coverage' bitmaps which indicate what fraction of each pixel are 'covered' by the font,
   /// and we need to translate those coverage values to appropriate gray-scale values for OpenGL 
   /// to use. 
   public double Gamma {
      get => mGamma;
      set {
         if (mGamma.EQ (value)) return;
         mGamma = value; mGammaMap = null;
         Bump ();
      }
   }
   double mGamma = 1.5;

   /// <summary>Handle for the entire Freetype library</summary>
   static HLibrary Library => sLazy2.Value;
   static readonly Lazy<HLibrary> sLazy2 = new (() => { Check (Init (out var lib)); return lib; });

   /// <summary>The line-to-line distance (in pixels)</summary>
   public int LineHeight => mLineHeight;
   int mLineHeight;

   /// <summary>Sets the pixel-size for subsequent use</summary>
   /// This regenerates all the glyphs with the new size
   public (int X, int Y) PixelSize {
      get => mPixelSize;
      set {
         mPixelSize = value;
         Check (SetPixelSizes (mFace, (uint)value.X, (uint)value.Y));
         mRec = Marshal.PtrToStructure<CFace> ((Ptr)mFace);
         var size = Marshal.PtrToStructure<SizeRec> (mRec.Size);
         mLineHeight = (int)(size.Height.Value + 0.5);
         Bump ();
      }
   }
   (int X, int Y) mPixelSize;
   CFace mRec;    // Marshalled struct from the C library

   /// <summary>Returns a large texture image that contains all the glyphs in the font</summary>
   /// The texture is always exactly 8192 pixels wide, and a certain number of pixels high (large
   /// enough to accomodate all the glyphs). It might be simpler to consider it as a single linear
   /// array of bytes, and each glphy then has a single integer TexOffset into this long buffer. 
   /// Suppose that glyph is 8 pixels wide and 12 pixels high. Then, starting at TexOffset, the
   /// first 8 bytes are the first row of the character (topmost row), the next 8 rows are the 
   /// next row. So the next consecutive 96 bytes encode this character. These bytes should be 
   /// treated as an (already gamma corrected) alpha value and can then be used for drawing the
   /// character. 
   /// See the Text.frag shader for code that takes the X,Y offsets into the character cell (which
   /// for this example would go from 0..7 in X and 0..11 in Y), and converts them into a linear 
   /// delta from 0..95 starting at that character's TexOffset into this long linear buffer. That
   /// shader has to also then convert this 'linear offset' into S,T coordinates into that texture,
   /// but that is simple since these textures are always exactly 8192 pixels wide 
   internal HTexture Texture {
      get {
         if (mTexture == 0) mTexture = BuildTexture ();
         return mTexture;
      }
   }
   HTexture mTexture;

   /// <summary>UID for this font (changes when the size changes!)</summary>
   public int UID => mUID;
   static int sNextUID;
   int mUID;

   // Methods ------------------------------------------------------------------
   /// <summary>Gets the glyph index for a particular char (0 if the char does not exist)</summary>
   public uint GetGlyphIndex (char ch) => Map.SafeGet (ch);

   /// <summary>Gets the kerning adjustment between two glyphs (specified by indices idx0, idx1)</summary>
   /// The kerning adjustment is rounded to the nearest integer (since we cannot handle fractional
   /// pixel positionings of glyphs)
   public int GetKerning (uint idx0, uint idx1) {
      // The atlas-loaded path uses a pre-baked table of (nonzero) kern pairs
      if (mKern != null) return mKern.TryGetValue (((ulong)idx0 << 32) | idx1, out var kern) ? kern : 0;
      GetCharKerning (mFace, idx0, idx1, 0, out var kerning);
      return (int)kerning.X.Value;
   }
   Dictionary<ulong, short>? mKern;

   /// <summary>Get metrics data for a given character</summary>
   public ref Metrics GetMetrics (char ch) => ref GetMetrics (GetGlyphIndex (ch));

   /// <summary>Get metrics data for a given glyph index</summary>
   public ref Metrics GetMetrics (uint n) => ref Notes[n];

   /// <summary>This 'measures' some text and returns the bounding box of it</summary>
   /// This assumes that we are drawing the text with a baseline-start at (0,0). As with all
   /// pixel coordinates, +Y goes downwards. So the 'top' of this returned rectangle will be
   /// a negative value (which is how many pixels the top of text extends above the baseline),
   /// and the 'bottom' of this returned rectangle will be a positive value (which will be how many
   /// pixels the text descends below the baseline). 
   /// <param name="text">The text to measure</param>
   /// <param name="exact">If set, the Y extents are tightly aligned to the extents of the
   /// given string of text. Otherwise, they are set to the general ascender / descender of this
   /// font, and are thus more useful for alignment, polanning and positioning</param>
   public RectS Measure (string text, bool exact = false) {
      uint idx0 = 0;
      int x = 0, y = 0, left = 9999, top = 0, right = 0, bottom = 0;
      foreach (var ch in text) {
         // Get the glyph index for this incoming char, then get the metrics for it
         // and the kerning between this and the previous char
         uint idx1 = GetGlyphIndex (ch);
         ref var metric = ref GetMetrics (idx1);
         int kern = GetKerning (idx0, idx1);
         int xChar = x + metric.LeftBearing + kern, yChar = y - metric.TopBearing;
         left = Math.Min (left, xChar); top = Math.Min (top, yChar);
         right = Math.Max (right, xChar + metric.Columns); bottom = Math.Max (bottom, yChar + metric.Rows);
         x += metric.Advance + kern;
         idx0 = idx1;
      }
      if (!exact) { bottom = mDescender; top = -mAscender; }
      if (right == 0) left = 0;
      return new (left, top, right, bottom);
   }

   /// <summary>Measures each character of the text and stores the potential cursor positions in xpos</summary>
   /// This is useful when we are rendering a text-box, and want to position the
   /// caret at a particular character in the text.
   public void GetCharsPos (string text, List<short> xpos, int xstart = 0) {
      xpos.Clear ();
      uint idx0 = 0;
      int x = xstart; xpos.Add ((short)x);
      foreach (var ch in text) {
         uint idx1 = GetGlyphIndex (ch);
         var metric = GetMetrics (idx1);
         int kern = GetKerning (idx0, idx1);
         x += metric.Advance + kern; xpos.Add ((short)x);
         idx0 = idx1;
      }
   }

   /// <summary>Sets the 'M' size in pixels</summary>
   public void SetEMSizeInPixels (int pixels) {
      Check (SetPixelSizes (mFace, 1000, 1000));
      var glyph = GetGlyph (GetGlyphIndex ('M'));
      uint size = (uint)(pixels * 1000.0 / glyph.Rows + 0.45);
      PixelSize = ((int)size, (int)size);
      double lie = -(double)mRec.Descender / (mRec.Ascender - mRec.Descender);
      mDescender = (int)(PixelSize.Y * lie + 0.5);
      mAscender = PixelSize.Y - mDescender;
   }
   public int Ascender => mAscender;
   public int Descender => mDescender;
   int mAscender, mDescender;

   /// <summary>Select a particular encoding (affects character to glyph conversions)</summary>
   internal void SetEncoding (FTEncoding encoding)
      => Check (FreeType.FreeType.SetEncoding (mFace, encoding));

   /// <summary>Serializes this typeface into a 'pre-baked atlas' (desktop only, uses FreeType)</summary>
   /// The atlas contains everything the renderer needs at runtime - glyph metrics, the
   /// char-to-glyph map, the (nonzero) kerning pairs and the gamma-corrected coverage
   /// texture - so that LoadAtlas can reconstruct a fully working TypeFace with no native
   /// code. This is how text works on browser-wasm, where FreeType is not available.
   /// Call this before the Texture property is read (building the GL texture discards the
   /// raw texture data this needs).
   public void SaveAtlas (Stream stm) {
      _ = Notes;     // Builds mNotes and mRawTexData
      var bw = new BinaryWriter (stm);
      bw.Write ("NGA1"u8);
      bw.Write (mPixelSize.X); bw.Write (mPixelSize.Y);
      bw.Write (mLineHeight); bw.Write (mAscender); bw.Write (mDescender);
      var notes = mNotes!;
      bw.Write (notes.Length);
      foreach (var m in notes) {
         bw.Write (m.Rows); bw.Write (m.Columns); bw.Write (m.LeftBearing);
         bw.Write (m.TopBearing); bw.Write (m.Advance); bw.Write (m.TexOffset);
      }
      _ = Map;
      bw.Write (mMap!.Count);
      foreach (var (ch, glyph) in mMap) { bw.Write ((ushort)ch); bw.Write (glyph); }
      // Gather the nonzero kerning pairs over all glyphs (sparse: a few thousand for
      // a typical font, versus millions of possible pairs)
      List<(uint A, uint B, short K)> kerns = [];
      var glyphs = mAllGlyphs!;
      foreach (var a in glyphs)
         foreach (var b in glyphs) {
            int k = GetKerning (a, b);
            if (k != 0) kerns.Add ((a, b, (short)k));
         }
      bw.Write (kerns.Count);
      foreach (var (a, b, k) in kerns) { bw.Write (a); bw.Write (b); bw.Write (k); }
      bw.Write (mRawTexData!.Length);
      bw.Write (mRawTexData);
   }

   /// <summary>Reconstructs a TypeFace from a pre-baked atlas (see SaveAtlas) - fully managed</summary>
   public static TypeFace LoadAtlas (byte[] data) {
      var br = new BinaryReader (new MemoryStream (data, writable: false));
      if (!br.ReadBytes (4).AsSpan ().SequenceEqual ("NGA1"u8))
         throw new IOException ("Not a Nori glyph atlas");
      TypeFace tf = new ();
      tf.mPixelSize = (br.ReadInt32 (), br.ReadInt32 ());
      tf.mLineHeight = br.ReadInt32 (); tf.mAscender = br.ReadInt32 (); tf.mDescender = br.ReadInt32 ();
      int cNotes = br.ReadInt32 ();
      tf.mNotes = new Metrics[cNotes];
      for (int i = 0; i < cNotes; i++)
         tf.mNotes[i] = new Metrics (br.ReadInt16 (), br.ReadInt16 (), br.ReadInt16 (),
                                     br.ReadInt16 (), br.ReadInt16 (), br.ReadInt32 ());
      int cMap = br.ReadInt32 ();
      tf.mMap = new Dictionary<char, uint> (cMap);
      for (int i = 0; i < cMap; i++) tf.mMap[(char)br.ReadUInt16 ()] = br.ReadUInt32 ();
      tf.mAllGlyphs = [.. tf.mMap.Values.Distinct ()];
      int cKern = br.ReadInt32 ();
      tf.mKern = new Dictionary<ulong, short> (cKern);
      for (int i = 0; i < cKern; i++) {
         ulong key = ((ulong)br.ReadUInt32 () << 32) | br.ReadUInt32 ();
         tf.mKern[key] = br.ReadInt16 ();
      }
      tf.mRawTexData = br.ReadBytes (br.ReadInt32 ());
      tf.mUID = ++sNextUID;
      return tf;
   }

   // Implementation -----------------------------------------------------------
   // Called whenever the font size is changed
   void Bump () {
      mNotes = null; mRawTexData = null;
      if (mTexture != 0) { GL.DeleteTexture (mTexture); mTexture = HTexture.Zero; }
      mUID = ++sNextUID;
   }

   // Helper used to build the GL texture (from the mRawTexData byte-buffer we construct
   // when we iterate through all the glyphs). 
   HTexture BuildTexture () {
      _ = Notes;  // This will also build the mRawTexData buffer
      GL.ActiveTexture (ETexUnit.Tex0);
      HTexture texture = GL.GenTexture ();
      GL.BindTexture (ETexTarget.TexRectangle, texture);
      GL.PixelStore (EPixelStoreParam.UnpackAlignment, 1);
      byte[] texData = mRawTexData!;
      GL.TexImage2D (ETexTarget.TexRectangle, EPixelInternalFormat.Red, CXTex, texData.Length / CXTex, EPixelFormat.Red, EPixelType.UByte, texData);
      if (OperatingSystem.IsBrowser ()) {
         // On WebGL2 the target maps to TEXTURE_2D, whose default MIN_FILTER expects
         // mipmaps - without explicit filters the texture is incomplete and samples black
         GL.TexParameter (ETexTarget.TexRectangle, ETexParam.MinFilter, (int)ETexFilter.Nearest);
         GL.TexParameter (ETexTarget.TexRectangle, ETexParam.MagFilter, (int)ETexFilter.Nearest);
      }
      mRawTexData = null;
      return texture;
   }
   const int CXTex = 8192;

   // Called to initialize the font with a specified pixel size
   void InitFont (int pixelSize) {
      mRec = Marshal.PtrToStructure<CFace> ((Ptr)mFace);
      SetEMSizeInPixels (pixelSize);
      Bump ();
   }

   public override string ToString ()
      => mKern != null ? $"TypeFace (atlas, {mPixelSize.X}px)" : $"{mRec.FamilyName.ToUTF8 ()} {mRec.StyleName.ToUTF8 ()}";

   // Returns the Glyph structure for a particular glyph index
   internal Glyph GetGlyph (uint glyphIdx) {
      Check (LoadGlyph (mFace, glyphIdx, 0));
      Check (RenderGlyph (mRec.Glyph, 0));
      mGlyph.Update (mRec.Glyph);
      return mGlyph;
   }
   readonly Glyph mGlyph = new ();

   /// <summary>Dictionary that maps characters to glyph indices</summary>
   IReadOnlyDictionary<char, uint> Map {
      get {
         if (mMap != null) return mMap;
         mMap = [];
         HashSet<uint> allGlyphs = [];
         foreach (var e in Encodings) {
            SetEncoding (e);
            uint charCode = GetFirstChar (mFace, out uint gindex);
            while (gindex != 0) {
               allGlyphs.Add (gindex);
               mMap[(char)charCode] = gindex;
               charCode = GetNextChar (mFace, charCode, out gindex);
            }
         }
         mAllGlyphs = [.. allGlyphs];
         return mMap;
      }
   }
   Dictionary<char, uint>? mMap;

   // This returns an array that contains the Metrics for every glyph in the
   // font. When this is read the first time, this enumerates through all the glyphs in the
   // font, and extracts the metrics (by first loading that Glyph into the TypeFace's single
   // glyph-slot and then fetching the metrics). It also rasterizes the font, and fetches the
   // pixels of the glyph. All these glphs are loaded into the huge byte-array (mRawTexData),
   // and along with each glyph's notes, we also store the TexOffset into this array. 
   // This big array can be turned into an OpenGL texture by simplying reading the HTexture
   // property (which constructs the OpenGL texture, and then discards this byte-array, which
   // is no longer needed). 
   unsafe Metrics[] Notes {
      get {
         if (mNotes != null) return mNotes;
         var glyphIndices = AllGlyphs;
         uint max = glyphIndices.Max ();
         mNotes ??= new Metrics[max + 1];
         byte[] texData = new byte[131072];
         int texOffset = 0;
         foreach (var index in glyphIndices) {
            if (mNotes[index].TexOffset > 0) continue;
            var g = GetGlyph (index);
            mNotes[index] = new Metrics (g, texOffset);
            int cb = g.Rows * g.Columns;
            if (cb > 0) {
               while (texOffset + cb >= texData.Length)
                  Array.Resize (ref texData, texData.Length * 2);
               if (g.Columns == g.Stride) {
                  fixed (void* pDst = &texData[texOffset])
                     Buffer.MemoryCopy (g.Buffer.ToPointer (), pDst, cb, cb);
               } else
                  throw new NotImplementedException ();
               texOffset += cb;
            }
         }
         byte[] gamma = GammaMap;
         for (int i = 0; i < texOffset; i++) texData[i] = gamma[texData[i]];
         texOffset = CXTex * ((texOffset + CXTex - 1) / CXTex);
         Array.Resize (ref texData, texOffset);
         mRawTexData = texData;
         return mNotes;
      }
   }
   byte[]? mRawTexData;

   // A pre-computed gamma map for the current Gamma
   byte[] GammaMap {
      get {
         if (mGammaMap == null) {
            mGammaMap = new byte[256];
            double f = 1 / Gamma;
            for (int i = 0; i < 256; i++) {
               double y = Math.Pow (i / 255.0, f);
               GammaMap[i] = (byte)(y * 255 + 0.5);
            }
         }
         return mGammaMap;
      }
   }
   byte[]? mGammaMap;

   // Nested types -------------------------------------------------------------

   public readonly struct Metrics {
      internal Metrics (Glyph g, int texOffset) {
         Advance = (short)g.Advance;
         (Rows, Columns) = ((short)g.Rows, (short)g.Columns);
         (LeftBearing, TopBearing) = ((short)g.LeftBearing, (short)g.TopBearing);
         TexOffset = texOffset;
      }

      // Used when deserializing a pre-baked atlas (see TypeFace.LoadAtlas)
      internal Metrics (short rows, short columns, short leftBearing, short topBearing, short advance, int texOffset)
         => (Rows, Columns, LeftBearing, TopBearing, Advance, TexOffset)
          = (rows, columns, leftBearing, topBearing, advance, texOffset);

      /// <summary>Rows and Columns of the bitmap</summary>
      public readonly short Rows, Columns;
      /// <summary>Left-bearing and Top-bearing (used to position the character) from baseline</summary>
      public readonly short LeftBearing, TopBearing;
      /// <summary>Advance width after rendering this character</summary>
      public readonly short Advance;
      /// <summary>Offset into the texture bitmap</summary>
      public readonly int TexOffset;
   }
   Metrics[]? mNotes;
}
#endregion
